info.app:
  name: HMPPS External Movements Api
  version: 1.0

spring:
  application:
    name: hmpps-external-movements-api

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}?sslmode=${DB_SSL_MODE}&reWriteBatchedInserts=true'
    username: ${DB_USER}
    password: ${DB_PASS}

    hikari:
      connectionTimeout: 1000
      validationTimeout: 500
      maximumPoolSize: 20
      auto-commit: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/schema,classpath:db/data

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 1000
          fetch_size: 1000
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        order_inserts: true
        order_updates: true
      org.hibernate.envers:
        audit_table_suffix: _audit
        revision_field_name: rev_id
        revision_type_field_name: rev_type
        modified_flag_suffix: _modified
        store_data_at_delete: true
        do_not_audit_optimistic_locking_field: false
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${integration.hmpps-auth.url}/.well-known/jwks.json

      client:
        registration:
          default:
            provider: hmpps-auth
            client-id: ${client.id}
            client-secret: ${client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${integration.hmpps-auth.url}/oauth/token

  http:
    codecs:
      max-in-memory-size: 10MB

sentry:
  exception-resolver-order: -2147483647

springdoc:
  paths-to-exclude: "/queue-admin/**"

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

service:
  active-prisons:
  domain-events:
    poll-interval: PT0s
  occurrence-status:
    poll-interval: PT0s
  authorisation-expiration:
    cron: ""

client:
  id: external-movements
  secret: external-movements

logging:
  level:
    org.springframework: INFO
    uk.gov.justice.digital: DEBUG
