hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomaineventsqueue:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: hmppseventtopic
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
