integration:
  hmpps-auth:
    url: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  manage-users:
    url:  "https://manage-users-api.hmpps.service.justice.gov.uk"
  prisoner-search:
    url: "https://prisoner-search.prison.service.justice.gov.uk"

service:
  ui-base-url: "https://external-movements.hmpps.service.justice.gov.uk"