integration:
  hmpps-auth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  manage-users:
    url:  "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
  prisoner-search:
    url: "https://prisoner-search-dev.prison.service.justice.gov.uk"

service:
  active-prisons: "LEI,MDI"
  domain-events:
    poll-interval: PT10s
  occurrence-status:
    poll-interval: PT60s