integration:
  hmpps-auth:
    url: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  manage-users:
    url:  "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
  prison-register:
    url: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
  prisoner-search:
    url: "https://prisoner-search-preprod.prison.service.justice.gov.uk"

service:
  active-prisons: "***"
  domain-events:
    poll-interval: PT0.1s
  occurrence-status:
    poll-interval: PT60s
  authorisation-expiration:
    cron: "0 0 7 * * *"
  ui-base-url: "https://external-movements-preprod.hmpps.service.justice.gov.uk"
