integration:
  hmpps-auth:
    url: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  manage-users:
    url:  "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
  prisoner-search:
    url: "https://prisoner-search-preprod.prison.service.justice.gov.uk"

service:
  active-prisons: "FDI,LYI,SPI"
  ui-base-url: "https://external-movements-preprod.hmpps.service.justice.gov.uk"
