---
# Per environment values which override defaults in hmpps-external-movements-api/values.yaml

generic-service:
  ingress:
    host: external-movements-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: prod
    SPRING_PROFILES_ACTIVE: prod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-prod
  rdsAlertsDatabases:
    cloud-platform-4dbf3982763d5579: "External Movements API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-external-movements-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-external-movements-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
