---
# Per environment values which override defaults in hmpps-external-movements-api/values.yaml

generic-service:
  ingress:
    host: external-movements-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: prod
    SPRING_PROFILES_ACTIVE: prod

  postgresDatabaseRestore:
    jobName: rem-prod-to-preprod-restore
    enabled: true
    timeout: 14400
    schedule: "0 2 * * *"
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
  rdsAlertsDatabases:
    cloud-platform-4dbf3982763d5579: "External Movements API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-external-movements-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-external-movements-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
