---
# Per environment values which override defaults in hmpps-external-movements-api/values.yaml

generic-service:
  ingress:
    host: external-movements-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    SPRING_PROFILES_ACTIVE: preprod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-alerts-api-non-prod
  rdsAlertsDatabases:
    cloud-platform-9a716c2a18a56ffc: "External Movements API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-external-movements-preprod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-external-movements-preprod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
