---
# Per environment values which override defaults in hmpps-external-movements-api/values.yaml

generic-service:
  ingress:
    host: external-movements-api-dev.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: dev
    SPRING_PROFILES_ACTIVE: dev

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
  rdsAlertsDatabases:
    cloud-platform-348213e2359f7b4e: "External Movements API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-external-movements-dev-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-external-movements-dev-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15

